version: '3.8'

services:
  application:
    container_name: app
    build: ../
    image: examples-with-spring-boot:latest
    ports:
      - 8081:8080
    environment:
      DB_URL: "jdbc:postgresql://database:5432/examples-with-spring-boot"
      DB_USERNAME: "username"
      DB_PASSWORD: "password"

  database:
    container_name: app-postgres
    image: postgres:latest
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "examples-with-spring-boot"
